url: http://restfb.com
baseurl: 

# Site settings
title: 
  default: restfb
  light: <span class="restfb-brand light">rest</span><span class="restfb-brand highlight">fb</span>
  dark: <span class="restfb-brand dark">rest</span><span class="restfb-brand highlight">fb</span>
description: "RestFB is a simple and flexible Facebook Graph API client written in Java. It contains support for the Facebook Messenger Platform and the Facebook Marketing API."

link:
  maven: https://mvnrepository.com/artifact/com.restfb/restfb
  github-example: https://github.com/restfb/restfb-examples

# code and explanantion
collections:
  documentation:
    title: Documentation
    render: true
    output: true

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 337ab7
  secondary: 337ab7  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Mark Allen
  pic: 1
  position: Founder
  social:
    - title: github
      url: http://bit.ly/2Hjo9QS
    - title: linkedin
      url: http://bit.ly/2VNlXV0

- name: Norbert Bartels
  pic: 2
  position: Maintainer and Lead Developer
  social:
    - title: github
      url: http://bit.ly/2AKeAVt
    - title: stack-overflow
      url: http://bit.ly/2QHetzd
    - title: xing
      url: http://bit.ly/2D7nnm5

- name: many contributors
  pic: 3

# site Social network links and types (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: Facebook
    icon: facebook
    url: https://www.facebook.com/Restfb-909653922461664
  - title: StackOverflow
    icon: stack-overflow
    url: http://stackoverflow.com/questions/tagged/restfb
  - title: GitHub
    icon: github
    url: http://github.com/restfb/restfb
  - title: Google Groups
    icon: users
    url: http://groups.google.com/group/restfb

# additional links
navigation:
  - text: Cookbook
    url: /cookbook/
  - text: Documentation
    url: /documentation/

clients:
   - name: Angry Birds
     url: https://apps.facebook.com/angrybirds/
     pic: img/clients/angry-birds-friends.min.png
   - name: Hubspot
     url: https://www.hubspot.com/
     pic: img/clients/hubspot.min.png
   - name: Atchik
     url: https://atchik.com/
     pic: img/clients/atchik.min.png
   - name: Khoros
     url: https://khoros.com/
     pic: img/clients/khoros.min.png
   - name: ITyX Solutions AG
     url: https://www.ityxsolutions.com/
     pic: img/clients/ityx.min.png
   - name: Nitro AI
     url: http://nitro.ai
     pic: img/clients/nitro-ai.min.png
   - name: Dwinq
     url: http://dwinq.com/
     pic: img/clients/dwinq.min.png
   - name: Sematell GmbH
     url: http://www.sematell.com/
     pic: img/clients/sematell.min.png	
   - name: Clover
     url: https://www.clover.com/
     pic: img/clients/clover.min.png	 
   - name: The Socialstation
     url: https://thesocialstation.com/
     pic: img/clients/thesocialstation.color.jpg
   - name: Sparkcentral
     url: https://www.sparkcentral.com/
     pic: img/clients/sparkcentral.min.png
   - name: Falcon.io
     url: https://www.falcon.io/
     pic: img/clients/falconio.min.png 
   - name: Friend2Friend
     url: http://www.friend2friend.com/
     pic: img/clients/friend2friend.min.png
   - name: Tynamo
     url: https://www.tynamo.org/
     pic: img/clients/tynamo.min.png
   - name: IBM
     url: https://www.ibm.com/
     pic: img/clients/ibm.min.png
   - name: nukesuite
     url: https://www.nukesuite.com/
     pic: img/clients/nukesuite.min.png

plugins:
  - jekyll-sitemap

sass:
  style: compressed

usecdn: true

# Build settings
markdown: kramdown
permalink: pretty

exclude: [README.md, LICENSE]